In [2]:
import numpy as np
import json
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="darkgrid")

with open("../statistic/airplane_car_flowerpot.json", 'r') as f:
    sdict = json.load(f)

class_sets = ["airplane", "car", "flower_pot"]

correct_ratio = []
gdth_ratios = []
err_rs = []
err_ts = []
err_xs = []
for cls in class_sets:
    gdth_ratios.append((np.array(sdict[cls]["gdth_set"]) / np.array(sdict[cls]["init_set"])).mean().item())
    correct_ratio.append(len(sdict[cls]["corr_set"]) / sdict[cls]["totl_cnt"])
    
    err_r = [r if r < 90.0 else 180.0 - r for r in sdict[cls]["err_R"]]
    err_rs.append(np.mean(err_r).item())
    err_ts.append(np.absolute(np.mean(sdict[cls]["err_t"])).item())
    err_x = [x if x < 90.0 else 180.0 - x for x in sdict[cls]["err_x"]]
    err_xs.append(np.mean(err_x).item())

sns.barplot(x=class_sets, y=err_xs)
# sns.barplot(x=class_sets, y=err_Rs)
plt.show()


FileNotFoundError: [Errno 2] No such file or directory: '../statistic/airplane_car_flowerpot.json'

In [1]:
import numpy as np
import utils

coords = np.random.random(size=(100, 3))
# print(coords)
print(utils.unit_sphere_norm(coords, 100.0))
print(utils.unit_sphere_norm(coords, 1.0))


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
[[ 52.38756129  -1.60123088  36.74901679]
 [ 60.56677697 -59.38477981 -33.34838755]
 [ 15.26836434 -26.36643412  20.53944642]
 [ 61.36501453 -51.7766584   55.91222794]
 [-12.14027491 -25.33540081  60.31373997]
 [-65.97129683 -36.12219009  22.59658174]
 [ 36.67010392  18.54136869 -41.57577529]
 [-22.7106163  -64.7171688  -67.83250119]
 [  1.32209529 -35.60988545 -70.70197211]
 [ 19.47702833  -1.64277953  58.92121663]
 [  5.4200465   42.25223014 -13.93304157]
 [-14.68226601  58.97663477  47.36835513]
 [ 65.71469463  -2.68159159  59.25461142]
 [ 27.14231575  34.50134603   1.67893585]
 [ 61.561008    46.96457624  42.77584743]
 [ 65.44091803  -1.20323049 -49.90938324]
 [-15.58657893 -16.30712281 -49.89214127]
 [  6.01664419  -3.1246596   57.86407662]
 [-68.68502458  54.39307086  -0.72687225]
 [-17.83320769 -18.82914076  32.0